version: '3'

services:
  web:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
    - .:/var/www/html/
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./mime.types:/etc/nginx/mime.types
    depends_on:
    - php
    - mysql
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "9000:9000"
    volumes:
    - .:/var/www/html/
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: "contweb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - contwebdata:/var/lib/mysql

volumes:
  contwebdata:
